# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    
    - name: Build & tag & push the Docker image
      run: |
        tag=$(grep "<version>" my-app/pom.xml | head -1)
        tag=$(echo $tag | awk '{ print substr( $0, 10, length($0)-19 )}')
        docker build . --file my-app/Dockerfile --tag ${{secrets.DOCKER_USER}}/java-hello-world:$tag
        docker push ${{secrets.DOCKER_USER}}/java-hello-world:$tag
        
    - name: Run the build process with Docker
      run: |
        docker run soup1c/java-hello-world:1.0.0
        
        
  change-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Change something
        run: |
          tag=$(grep "<version>" my-app/pom.xml | head -1)
          tag=$(echo $tag | awk '{ print substr( $0, 10, length($0)-19 )}')
          semVer=${tag//./ }
          read -a semVer <<< $semVer
          (( semVer[2]++ ))
          newVersion=${semVer[@]}
          newVersion=${newVersion// /.}
          echo $newVersion
          echo "replacing pom.xml versionning."
          sed "s/$tag/$newVersion/g" my-app/pom.xml
          
          
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Replaced semantic versioning
        
        
        
# This is a failing kubernetes cluster.
#




#       - run: |
#         releaseVersion=$(curl --silent "https://api.github.com/repos/knicknic/temp-kubernetes-ci/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
#         curl -sSL "https://github.com/KnicKnic/temp-kubernetes-ci/releases/download/$releaseVersion/linux.sh" | sh        
        
        
#       - name: Github Action | Helm Deployment
#         uses: crazyfree/helm-deploy-githhub-action@v1.0.5
#         with:
#           release: hello-world-java
#           namespace: default
#           chart: /my-app/helm
