# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


    - name: Build with Maven
      run: mvn -B package --file my-app/pom.xml


    - name: pre-Dockerization
      run: |
        ls -la my-app/target/
        mkdir artifacts
        mv my-app/target/my-app* artifacts/
        echo "showing whats inside artifacts/"
        ls -la artifacts/
        
        
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    
    - name: Build the Docker image
      run: |
        artifact=$(find artifacts/ -name "my-app*")
        tag="${artifact:17}"
        tag="${tag%.*}"
        echo "$tag"
        docker build . --file my-app/Dockerfile --tag ${{secrets.DOCKER_USER}}/java-hello-world
        
        
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/java-hello-world
